name: Build test images

on:
  push:
    branches: [ master ]

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: github/super-linter@v3
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      # QEMU is used to emulated the ARM architecture, allowing us
      # to build not-x86 images
      - uses: docker/setup-qemu-action@master
        with:
          platforms: all
      # Buildx provides an easier way of building Docker images for other architectures
      - uses: docker/setup-buildx-action@master
      - name: Build image
        run: |
          docker buildx build --platform=linux/arm,linux/arm64,linux/amd64 --load -t graphiteapp/graphite-statsd:test .
      - name: Run Snyk to check Docker image for vulnerabilities
        uses: snyk/actions/docker@master
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          command: monitor
          image: graphiteapp/graphite-statsd:test
          args: --file=Dockerfile --platform=linux/arm,linux/arm64,linux/amd64 --project-name=graphite-project/docker-graphite-statsd
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
      # Use the build cache and push the imagee
      - name: Push image to Docker Hub
        run: |
          docker buildx build --platform=linux/arm,linux/arm64,linux/amd64 --push -t graphiteapp/graphite-statsd:test .